### ISSUE TITLE
There is a curly braces error in Onay page 

### ISSUE THREAD

**Issue by CumaliTurkmenoglu** [ondes/Template-Latex-ITU-Thesis#15]
The boldened curly braces should be removed otherwise the part within appears after the second part that starts with "student ID..."

	\begin{textblock*}{\textwidth}[0,0](40mm,50.5mm)
	{\th@isimsoyisim}, { a} \if@Doktora { Ph.D.}\ \fi  \if@YuksekLisans  { M.Sc.}\ \fi \if@Lisans { B.Sc.}\ \fi student of
	ITU~\if@YuksekLisans **{** \th@Institute~\th@Instituteiki\ \fi \if@Doktora \th@Institute~\th@Instituteiki\ \fi \if@Lisans \if@ElektrikElektronik \th@Institute~\th@Instituteiki \fi \fi **}** student ID \th@ogrencino,\ successfully defended the {\if@Lisans graduation project\ \fi \if@YuksekLisans thesis\ \fi \if@Doktora dissertation\ \fi}entitled {``{\Baslikbir\ifthenelse{\equal{\Baslikiki}{}}{}{
	\Baslikiki\ifthenelse{\equal{\Baslikuc}{}}{}{\
	\Baslikuc}}}''}, which he/she prepared after fulfilling the requirements specified in the associated legislations, before the jury whose signatures are below.
    \end{textblock*}

**Comment by ondes** [comment]
Thanks for informing us. I updated the class file accordingly.
